[project]
name = "aiviz"
version = "0.1.0"
description = "LLM activation visualizer web app."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "accelerate>=1.15.0",
    "altair>=6.3.0",
    "huggingface-hub>=1.32.0",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "pandas-stubs>=3.0.5.260914",
    "streamlit>=1.64.0",
    "torch>=2.14.0",
    "transformers>=5.17.0",
]

[server]
fileWatcherType = "none"

[dependency-groups]
dev = [
    "ruff>=0.16.8",
    "torchvision>=0.29.0",
    "ty>=0.0.83",
]
